### ISSUE TITLE
Serialisation manuelle des objets et leurs dépendances (synchro)

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#109]

**Comment by chfivet** [comment]
@basmot @htmfilho Dois-je réaliser des tests comme nous avions fait hier ?

**Comment by htmfilho** [comment]
Salut @chfivet , oui. Tu peux mettre à jour la branche 109 d'osis-common. Merci.

**Comment by htmfilho** [comment]
Salut @verpoorten , peux-tu tester de ton coté? Merci.

**Comment by chfivet** [comment]
@basmot @htmfilho @verpoorten Pour rappel, il fautrécupérer les branches feature/109 de osis-common sur Osis et Osis-Portal et il faut modifier le fichier backoffice/wsgi.py qui doit utiliser process_message au lieu de insert_or_update et idem dans frontoffice/wsgi.py
