### ISSUE TITLE
[ integration ] Créer automatiquement la librairie/bibliothèque lors de chaque push dans master

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#11]
- [x] Dev : 
  - Lors du push , les test unitaires sont lancés.
  - Le test SonarQube est lancé
-  [ ] Prod : 
  - Lors du push les tests unitaires sont lancés.
  - Si les test unitaires sont OK , la branche master est taguée , et la branche package est mise à jour.

**Comment by glamarca** [comment]
Pour le moment je n'ai pas trouvé une façon simple et sure de'automatiser la création du package.
A chercher

**Comment by htmfilho** [comment]
Pas besoin de tester en `prod` si les tests passe en `dev`.
