### ISSUE TITLE
Gestion du champs 'changed'

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#114]
Pour optimiser la synchronisation : on peut éviter de faire un update en comparant le champs `changed` du persisted_object avec l'objet qui vient de la queue.

- Comment gérer la valeur du champs changed? Sachant que Legacy-sync fournit la valeur de ce champs
- Comment l'ajouter à tous les modèles qui en ont besoin?

**Comment by htmfilho** [comment]
@basmot est-ce toujours le cas?

**Comment by basmot** [comment]
@htmfilho Ce n'est plus vraiment d'actualité car on va utiliser du SQL natif plutôt que de passer par les queues pour Legacy-sync. Et pour la sync Osis - Osis-portal, on n'a pas de problème de performance actuelleemnt pour les quelques dizaines de records échangés.
