### ISSUE TITLE
Ignorer les champs privés d'un objet ?

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-common#146]
QName: osis

    Date: None

    ExceptionTitle: DoesNotExist

    Exception: Traceback (most recent call last):
      File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/fields/related_descriptors.py", line 160, in __get__
        rel_obj = getattr(instance, self.cache_name)
    AttributeError: 'DissertationDocumentFile' object has no attribute '_document_file_cache'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/osis/www/html/osis_backend/backoffice/../osis_common/queue/callbacks.py", line 66, in process_message
        body = serializable_model.unwrap_serialization(json_data_dict)
      File "/home/osis/www/html/osis_backend/backoffice/../osis_common/models/serializable_model.py", line 172, in unwrap_serialization
        model_class.objects.filter(uuid=fields.get('uuid')).delete()
      File "/home/osis/www/html/osis_backend/backoffice/../osis_common/models/serializable_model.py", line 52, in delete
    obj.delete()
      File "/home/osis/www/html/osis_backend/backoffice/../osis_common/models/serializable_model.py", line 101, in delete
        ser_obj = serialize(self)
      File "/home/osis/www/html/osis_backend/backoffice/../osis_common/models/serializable_model.py", line 182, in serialize
    attribute = getattr(obj, f.name)
      File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/fields/related_descriptors.py", line 169, in __get__
    rel_obj = qs.get()
      File "/home/osis/VENV/lib/python3.4/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
    osis_common.models.document_file.DoesNotExist: DocumentFile matching query does not exist.

    Message: {'body': {'last_sync': None, 'fields': {'id': None, 'uuid': '56bf503c-6c6e-4771-85ae-9be5133cb990', 'document_file': {'last_sync': None, 'fields': {'file_name': 'Glaude Manon_Mémoire 2017-2018_Problématique et Bibliographie.pdf', 'size': 577545, 'update_by': 'mglaude', 'creation_date': 1487851387.0, 'description': '', 'content_type': 'application/pdf', 'uuid': 'e9de314d-0bcb-4f85-b38d-90df2ce44ea9', 'id': 39, 'storage_duration': 1830, 'application_name': 'dissertation', 'file': 'files/Glaude_Manon_Mémoire_2017-2018_Problématique_et_Bibliographie.pdf'}, 'model': 'osis_common.DocumentFile'}, 'dissertation': {'last_sync': None, 'fields': {'proposition_dissertation': {'last_sync': None, 'fields': {'created_date': 1477638066.0, 'visibility': True, 'author': {'last_sync': None, 'fields': {'available_at_office': False, 'available_by_email': False, 'comment': '', 'available_by_phone': False, 'uuid': 'b913cc5f-29fc-4420-9597-ab868dcdb975', 'id': 115, 'person': {'last_sync': None, 'fields': {'external_id': 'osis.person_00023379', 'gender': 'M', 'national_id': '65080500901', 'last_name': 'Liegeois', 'global_id': '00023379', 'email': 'michel.liegeois@uclouvain.be', 'phone': None, 'changed': 1487691188.0, 'phone_mobile': None, 'middle_name': None, 'uuid': 'dcb72f12-1f49-4586-a878-656bc6666e22', 'id': 11813, 'first_name': 'Michel', 'language': 'fr-be'}, 'model': 'base.Person'}, 'type': 'PRF'}, 'model': 'dissertation.Adviser'}, 'creator': {'last_sync': None, 'fields': {'external_id': 'osis.person_00023379', 'gender': 'M', 'national_id': '65080500901', 'last_name': 'Liegeois', 'global_id': '00023379', 'email': 'michel.liegeois@uclouvain.be', 'phone': None, 'changed': 1487691188.0, 'phone_mobile': None, 'middle_name': None, 'uuid': 'dcb72f12-1f49-4586-a878-656bc6666e22', 'id': 11813, 'first_name': 'Michel', 'language': 'fr-be'}, 'model': 'base.Person'}, 'collaboration': 'FORBIDDEN', 'description': '', 'active': True, 'level': 'THEME', 'title': "La place de l'outil militaire dans les strat!
     3;gies contre-terroristes", 'uuid': 'c33e20f9-b77c-476a-ab7e-cbe9a3e7a097', 'id': 335, 'max_number_student': 2, 'type': 'EMP'}, 'model': 'dissertation.PropositionDissertation'}, 'location': {'last_sync': None, 'fields': {'uuid': 'a2847ef6-14ee-4b86-a651-cd6c1bffb876', 'id': 1, 'name': 'Louvain-la-Neuve'}, 'model': 'dissertation.DissertationLocation'}, 'description': "À l’heure actuelle, le conflit en Syrie implique un nombre important d’acteurs et, ce, à différents niveaux. Ainsi, à un niveau international, nous noterons ici l’implication des États-Unis et des États occidentaux d’un côté, et celle de la Russie et de ses alliés de l’autre. Deux visions du conflit syrien s’opposent dès lors, que ce soit en ce qui concerne les méthodes à privilégier pour la résolution du conflit, que les objectifs recherchés. Karim Emile Bitar a d’ailleurs fait un parallèle entre le « bras de fer américano-russe »1 et les relations entre ces deux pays pendant la guerre froide.  \r\n\r\n  La littérature scientifique occidentale comporte un nombre important d’ouvrages et d’articles traitant du sujet et émettant diverses hypothèses quant à la raison de l’implication de la Russie dans le conflit syrien. L’une de ces explications consiste à dire que la Russie cherche avant tout à préserver ses intérêts économiques et militaires dans la région du Moyen-Orient et, ce, grâce au maintien du régime de Al-Assad. En outre, intervenir dans le conflit syrien serait l’occasion pour la Fédération de Russie de rétablir sa puissance sur la scène internationale. \r\n\r\n  Cependant, le conflit syrien est une crise complexe, et les analyses occidentales ne constituent qu’une face de la réalité. Pour ne citer qu’un exemple, loin de ne se soucier que de des intérêts éco!
     nomiques de la Russie et de sa domination sur le Moyen-Orient, le politologue russe Andreï Gratchev expliquait combien l’une des inquiétudes premières était « au sujet d'un foyer de tensions qui comporterait des perspectives d'aggravation tout à fait imprévisibles à proximité des frontières russes. Mais aussi à l'intérieur de la Russie ou dans son voisinage le plus proche »2.\r\n\r\n  L’objectif de ce mémoire serait dès lors de confronter l’idée d’un renouveau de la puissance de la Fédération de Russie sur la scène internationale à la grille de lecture russe du conflit en Syrie. Au travers d’une analyse des discours russes, il sera ainsi possible de voir si, effectivement, cet objectif de s’établir comme grande puissance se retrouve dans les déclarations russes. En d’autres mots, ce mémoire s’efforcerait de répondre à la question suivante : de quelle manière la Russie perçoit-elle le conflit en Syrie ?   \r\n\r\n  Pour pouvoir traiter cette problématique, il serait nécessaire d’aborder la notion de puissance, de donner une explication des principaux acteurs du conflit syrien ainsi qu’une explication du système politique de la Russie avant de pouvoir analyser les discours russes. \r\n\r\n1 BITAR K., « « La Syrie, foyer de déstabilisation régionale ?  », dans Confluences Méditerranée, 2014/2, n°89, p. 76 \r\n2 Propos de Andreï Gratchev, cité par :  HERARD P., « Syrie : comprendre la position russe », dans TV5 Monde, publié le 29 août 2013, mis à jour le 2 décembre 2013, page consultée le 21 février 2017, http://information.tv5monde.com/info/syrie-comprendre-la-position-russe-4477", 'active': True, 'status': 'DRAFT', 'title': 'La puissance de la Fédération de Russie sur la scène internationale : Grille de !
     lecture russe du conflit en Syrie.', 'author': {'last_sync': None, 'fields': {'uuid': '027c7f49-8338-4518-a5b6-17372d46de02', 'id': 32097, 'person': {'last_sync': None, 'fields': {'external_id': 'osis.person_00303572', 'gender': 'F', 'national_id': '', 'last_name': 'Glaude', 'global_id': '00303572', 'email': None, 'phone': None, 'changed': 1487691188.0, 'phone_mobile': None, 'middle_name': 'Danielle, Y.', 'uuid': '5eeec0e9-d2f2-4cff-a322-a294633233a5', 'id': 55841, 'first_name': 'Manon', 'language': 'fr-be'}, 'model': 'base.Person'}, 'registration_id': '34441300'}, 'model': 'base.Student'}, 'modification_date': 1487851425.0, 'defend_periode': 'UNDEFINED', 'defend_year': 2018, 'uuid': '4823cc5d-7144-406c-af78-e6dc4b7fa253', 'id': 256, 'creation_date': 1487851295.0, 'offer_year_start': {'last_sync': None, 'fields': {'offer': {'last_sync': None, 'fields': {'uuid': 'aa735318-6332-4a64-b459-0d1d12099189', 'external_id': 'osis.offer_164551', 'id': 2627, 'title': 'Master en sciences politiques, orientation relations internationales, à finalité spécialisée'}, 'model': 'base.Offer'}, 'title': 'Master en sciences politiques, orientation relations internationales, à finalité spécialisée', 'enrollment_enabled': True, 'acronym': 'SPRI2MS/DI', 'external_id': 'osis.offer_year_4405102_2016', 'grade_type': {'last_sync': None, 'fields': {'adhoc': False, 'institutional_grade_type': 'MASTER_120', 'coverage': 'UNIVERSITY', 'external_id': 'osis.reference.grade_type_university_82', 'language_exam_required': False, 'uuid': 'f002eb32-d5bb-464e-b3e6-a337848cceb0', 'id': 18, 'institutional': True, 'name': 'Master en 120 crédits à finalité spécialisée'}, 'model': 'reference.GradeType'}, 'subject_to_quota': False, 'title_international': 'Master [120] in Political Sciences: International Relations, Professional Focus', 'uuid': 'edff9fae-284a-4428-b4f7-5f362b4a9dae', 'id': 12, 'academic_year': {'last_sync': None, 'fields': {'year': 2016, 'external_id': 'VALIDITE_2016', 'id': 2, !
     'end_date': 1506722400.0, 'uuid': '3bda9e2a-d635-41b3-8d6d-01149244a1d8', 'start_date': 1473890400.0}, 'model': 'base.AcademicYear'}, 'campus': {'last_sync': None, 'fields': {'uuid': '6f207107-bcf0-4b38-a622-9e78a3540c99', 'external_id': 'osis.campus_3', 'id': 7, 'organization': {'last_sync': None, 'fields': {'external_id': 'osis.organization_UCL', 'reference': None, 'uuid': 'f2f4c5dc-c8c3-4544-bbca-47b10206f9cc', 'website': None, 'id': 1, 'acronym': 'UCL', 'name': 'Université catholique de Louvain', 'type': 'UNKNOWN'}, 'model': 'base.Organization'}, 'name': 'Louvain-la-Neuve'}, 'model': 'base.Campus'}}, 'model': 'base.OfferYear'}}, 'model': 'dissertation.Dissertation'}}, 'model': 'dissertation.DissertationDocumentFile'}, 'to_delete': True}

**Comment by htmfilho** [comment]
@basmot Ce problème, a-t-il été résolu dans un autre ticket? Nous ne l'avons pas vu depuis un certain temps.

**Comment by basmot** [comment]
@htmfilho Difficile à dire. C'est une erreur qui concerne Dissertation.
