### ISSUE TITLE
Use uuid as filename to store files

### ISSUE THREAD

**Issue by matgerard** [uclouvain/osis-common#164]
We have encoding problems with commas in filenames when uploading/downloading files.
As discussed with @glamarca it should be a great idea to store files using their uuid as filename in the filesystem.

**Comment by htmfilho** [comment]
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 23: ordinal not 
        in range(128)
    (8 additional frame(s) were not displayed)
    ...
      File "dissertation/views/upload_dissertation_file.py", line 41, in download
        content_type=dissertation_document.document_file.content_type)

https://sentry.osis.uclouvain.be/uclouvain/osis/issues/33924/
