### ISSUE TITLE
Add "End date" column on score's PDF

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-common#166]
Add 'end_date' column on PDF score encoding for each students

**Comment by basmot** [comment]
Ticket dépendant de l'issue 2072 dans Osis. Comme elle n'a pas été mergé dans cette release, on ne mettra pas à jour la référence d'Osis-common vers cette issue-ci. Non testable en Dev donc, on créera une nouvelle issue si nécessaire.
