### ISSUE TITLE
Sur le pdf de la feuille de notes, tenir compte du nombre d'étudiants inscrits pour afficher "étudiant" au singulier ou au pluriel

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-common#172]
@mahianth commented on [Wed May 03 2017](https://github.com/uclouvain/osis/issues/2159)

**En tant que** [rôle d'utilisateur]

**Je veux** [le but]

**de sorte que** [quelque raison].

**lien vers la documentation** :

**Comment by albrugnetti** [comment]
@mahianth Peux-tu vérifier en dev que l'on prend bien en compte le singulier/pluriel sur le PDF? 
@thuyhanghoang Peux-tu vérifier la légende ainsi que la correction de la date de délibération sur les feuilles de notes ?

**Comment by thuyhanghoang** [comment]
ok en dev
