### ISSUE TITLE
Vérifier l'algorithme de consommation des messages "to_delete" dans la queue

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#176]
Problématique : il y a parfois des insconsistance entre la DB Osis et Osis-portal. (Entre autre pour dissertation et pour internship).
Constat : après l'exécution d'un script python de correction de données (directement sur le serveur Osis), qui consistait à supprimer plusieurs records dans attribution.Attribution (via l'ORM - Object.delete()), certains LearningUnitYear n'existaient plus dans Osis-portal, alors qu'ils existaient toujours dans Osis (vérifié via Legacy-sync - la synchro a planté car des FK étaient inexistantes côté Osis-portal). 
A vérifier : lorsqu'un record est supprimé dans Osis, est-il bien supprimé côté Osis-portal? L'algorithme ne supprimerait-il pas aussi les foreign key de l'objet supprimé (alors qu'il ne devrait pas)?

**Comment by htmfilho** [comment]
On arrive pas a le reproduire.

**Comment by htmfilho** [comment]
Stress test.
