### ISSUE TITLE
Problème sur des feuilles de notes imprimées à partir du bureau virtuel des profs

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-common#178]
@thuyhanghoang commented on [Thu May 11 2017](https://github.com/uclouvain/osis-portal/issues/1069)

![image](https://cloud.githubusercontent.com/assets/6651769/25948528/28df918e-3654-11e7-8cdb-01471769cf22.png)

![image](https://cloud.githubusercontent.com/assets/6651769/25997360/fc17847c-371b-11e7-86fe-80d3529500d3.png)

**Comment by htmfilho** [comment]
@matgerard  Il faut déplacer la clé de traduction `link_to_RGEE` vers osis-common. Est-ce que le déplacement que @albrugnetti a fait règle le problème?

**Comment by matgerard** [comment]
@htmfilho oui c'est cela, @albrugnetti a déplacé les traductions communes y compris `link_to_RGEE`.
