### ISSUE TITLE
Changer le texte dans le pied de page des feuilles de notes

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-common#181]
@thuyhanghoang commented on [Tue May 16 2017](https://github.com/uclouvain/osis/issues/2277)

Remplacer "Règlement Général des Examens" par "Règlement général des études et des examens"

**Comment by thuyhanghoang** [comment]
J'ai lancé l'impression des feuilles de notes en Dev, j'ai toujours l'ancien texte =>????
![image](https://cloud.githubusercontent.com/assets/6651769/26204631/9d0a3cc2-3bdf-11e7-854b-744f1de49bc7.png)

**Comment by matgerard** [comment]
@thuyhanghoang c'est ok maintenant, peux-tu vérifier et fermer le ticket si c'est ok ? Merci !

**Comment by thuyhanghoang** [comment]
j'ai essayé d'imprimer les feuilles de notes dans OSIS et OSIS-Portail, ok pour les 2
