### ISSUE TITLE
Changer le message d'erreur en cas d'erreur lors de l'envoi d'un mail/message

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#189]
Lié à uclouvain/osis#2339.

- [x] Changer le message: Un problème technique est survenu, aucun message n'a été envoyé.
- [x] Ajouter des logs serveurs dans le cas ou il n'y a pas de destinataire ou pas de template html.

**Comment by basmot** [comment]
@thuyhanghoang @glamarca Enfait, ce message est affiché dans 2 cas :  
- soit c'est parce qu'il n'y a pas de template html
- soit c'est pcq il n'y a pas de destinataires

Je propose donc d'avoir 2 messages différents à la place de celui proposé : 
- "Aucun template html n'a été trouvé ; aucun mail n'a été envoyé."
- "Aucun destinataire n'a été fourni ; aucun mail ,'a été envoyé."

**Comment by thuyhanghoang** [comment]
@basmot le message que tu proposes est pour le cas générique. Pour ce cas ci, on est d'accord de ne pas afficher le message aux gestionnaires s'il n'y a pas de mail envoyé car il n'y a pas d'enseignant, c'est juste?

**Comment by htmfilho** [comment]
@basmot le message "Aucun template html ..." me semble très technique. Les utilisateurs ne comprendront pas.

**Comment by basmot** [comment]
@thuyhanghoang On est d'accord, dans les deux cas, aucun message ne sera affiché à l'utilisateur (il n'a pas besoin de savoir qu'il manque un template html, ni besoin de savoir qu'il n'y a pas de destinataire).

**Comment by basmot** [comment]
OK en Dev.
