### ISSUE TITLE
Create a decorator checking that the request is ajax

### ISSUE THREAD

**Issue by matgerard** [uclouvain/osis-common#194]
In some views, we check that the request is ajax (`if request.is_ajax()`).
Some examples in this file : `osis-portal/assessments/views/score_encoding.py `
It could be more readable to have a decoracor `@ajax_required` checking this for us.

See [this link](https://stackoverflow.com/questions/34152909/django-custom-decorator-to-allow-only-ajax-request) to see how to implement this decorator.

**Comment by htmfilho** [comment]
C'est intéressant d'avoir l'avis de @matrixise .

**Comment by matrixise** [comment]
Yep, it's a good idea, you can do it.

**Comment by htmfilho** [comment]
Jira.
