### ISSUE TITLE
Ajout de types de description dans document_file pour les uploads des pré-requis

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-common#22]
Crée pour le ticket [osis-portal 50](https://github.com/uclouvain/osis-portal/issues/50)

@glamarca !!! Faire le pull request avant le pull request du ticket osis-portal 50 !!!

**Comment by glamarca** [comment]
@verpoorten 
Ce serait mieu de mettre la remarque dans le ticket 50 de osis-portal!
