### ISSUE TITLE
[Messaging] Pouvoir réenvoyer un fichier depuis l'administration de message_history

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-common#52]

**Comment by htmfilho** [comment]
Pas claire. Pourquoi?

**Comment by verpoorten** [comment]
Il semblerait que ce soit un person.id qui soit stocké dans le champ receiver.  Hors cela vient du module base!  
Le ticket n'est pas prêt!

**Comment by glamarca** [comment]
Le receiver est l'id de la classe représentant la personne qui y est attachée.
Si on est dans le cas d'admission, ce sera un applicant.id, dans le cas de dashboard, ce sera un person.id.
C'est pour cette raison que le champ n'est pas une FK, mais un champ simple, il n'y a donc pas de dépendance vers un modèle (ni base ni admission)

**Comment by htmfilho** [comment]
Le problème c'est que pour pouvoir réenvoyer un message, le code a besoin du email qui n'est pas disponible dans la table `message_history`. Le code ne peux pas chercher le bon email avec l'id de la personne.

@glamarca  Ce ticket, il est lié à quel application, en fait? C'est quoi le besoin d'origine?

**Comment by glamarca** [comment]
SI je me souviens bien, c'est lié à l'encodage des notes.
La possibilité pour un admin de renvoyer un mail envoyer lors de l'encodage des notes.
Au début c'était une FK vers personne qu'il y avait dans la table, et donc on récupérait le mail de personne. Mais avec le passage à osis-portal, et les diff entre person et applicant, il a fallu le rendre indépendant.
Maintenant qu'il n'y a plus de différence, c'est peut-être le moment de revoir le modèle.

**Comment by htmfilho** [comment]
D'accord. Comme il y a déjà une liste de priorités pour l'encodage de notes et l'email n'est pas critique pour ces priorités on va attendre qui le besoin arrive pour le faire. 

Merci pour le contexte.
